pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'echo "build"'
            }
        }
        stage('test') {
            steps {
                sh 'echo "test"'
            }
        }
        stage('analyse') {
            steps {
                sh 'echo "analyse"'
            }
        }
        stage('deploy') {
            steps {
                sh 'aws --version'
            }
        }
    }
}