pipeline {
    stages {
        stage('build') {
            steps {
                sh 'echo "build"'
            }
        }
        stage('test') {
            steps {
                sh 'echo "test"'
            }
        }
        stage('analyse') {
            steps {
                sh 'echo "analyse"'
            }
        }
        stage('deploy') {
            agent { docker { image 'jenkins/aws-cli' }}
            steps {
                sh 'aws --version'
            }
        }
    }
}